
# Example of assembly for lma, using maxfit 

```{r}
#library(plant)
#library(plant.assembly)
devtools::load_all("../plant-dev")
devtools::load_all()

plant_log_console()

# Establish baseline parameters
plant_control <- function() {
  ctrl <- scm_base_control()
#  ctrl$equilibrium_nsteps <- 20
#  ctrl$equilibrium_solver_name <- "hybrid"
  ctrl$equilibrium_nsteps <- 80
  ctrl$equilibrium_solver_name <- "iteration"
  ctrl
}

p <- scm_base_parameters("FF16")
p$strategy_default$a_l1 <- 2.17
p$strategy_default$a_l2 <- 0.5
p$strategy_default$hmat <- 10

#p$max_patch_lifetime <- 150 # three species
p$max_patch_lifetime <- 60 # two species
#p$max_patch_lifetime <- 10 # one species

bounds0 <- bounds(lma = c(0.01, 1))

# change some of the controls on assembly
control <- assembler_control(
  list(
    run_type = "to_equilibrium",
    birth_type = "maximum",
    birth_move_tol = 1,
    compute_viable_fitness = FALSE,
    equilibrium_eps = plant_control()$equilibrium_eps
  )
)

# setup an empty community
community0 <- 
  community_start(
    p, 
    bounds0,
    fitness_approximate_control = list(type = "gp")
  )

# setup the assembler
obj <- 
  assembler_start(
    #community0, 
    obj1$history[[10]],
    control = control
  )

obj <- assembler_run(obj, nsteps = 20)

#saveRDS(obj, "obj.rds")
obj1 <- readRDS("obj.rds")

```

Now lets' look at the results

How many species in the community?
```{r}
obj$community$traits
obj$community$birth_rate
```

```{r}
library(dplyr)
library(ggplot2)
landscape <- obj$community$fitness_approximate_points %>% as_tibble()
ggplot(landscape, aes(hmat, fitness)) + 
  geom_line() +
  scale_x_log10() +
  geom_point(data = tibble(lma = obj$community$traits[,1], fitness = approx(landscape$lma, landscape$fitness,  obj$community$traits[,1])$y), col="red")
```

# Height

```{r}


         lma birth_rate
1 0.03886086   277.2675
2 0.19630583   18.42347
3 0.11070529   67.25629
4 0.25085100   2.852756



p <- scm_base_parameters("FF16")
p$strategy_default$a_l1 <- 2.17
p$strategy_default$a_l2 <- 0.5
p$strategy_default$hmat <- 10
p$strategy_default$lma <- 0.038

p$max_patch_lifetime <- 60 # two species

bounds0 <- bounds(hmat = c(0.5, 30))

# setup an empty community
community0 <-
  community_start(
    p,
    bounds0,
    fitness_approximate_control = list(type = "gp")
  )

# setup the assembler
obj <-
  assembler_start(
    community0,
    control = control
  )

obj <- assembler_run(obj, nsteps = 20)

```
