
# Example of stochastic assembly

```{r, setup}
library(plant)
library(plant.assembly)
 devtools::load_all()
# devtools::load_all("../plant-dev")

plant_log_console()

# Controls on plant package
plant_control <- function() {
  ctrl <- scm_base_control()
  ctrl$equilibrium_nsteps <- 80
  ctrl$equilibrium_solver_name <- "iteration"
  ctrl
}

# Establish baseline parameters
p <- scm_base_parameters("FF16")
p$strategy_default$a_l1 <- 2.17
p$strategy_default$a_l2 <- 0.5
p$max_patch_lifetime <- 60

```
# 1 trait: lma

## Assembly

```{r}

# Absolute bounds
bounds0 <- bounds(lma = c(0.01, 1))

# controls on assembly
control <- assembler_control(
  list(
    run_type = "single",
    birth_type = "stochastic",
    vcv = diag(1)
  )
)

# setup the assembler to start with empty community
community0 <-
  community_start(
    p,
    bounds0
  )

obj <- 
  assembler_start(
    community0, 
    control = control
  )

# run assembler
obj <- assembler_run(obj, nsteps = 100)

saveRDS(obj, "output/stochastic.rds")
```

Might want to caluclate fitness landscape for assembled community

```{r}

```

## Analysis




# 2 trait: lma + hmat

## Assembly

```{r}

bounds0 <- bounds(lma = c(0.01, 1), hmat = c(0.5, 30))

# controls on assembly
control <- assembler_control(
  list(
    run_type = "single",
    birth_type = "stochastic",
    compute_viable_fitness = FALSE,
    vcv = diag(2)
  )
)

# setup the assembler to start with empty community
community0 <- 
  community_start(
    p, 
    bounds0
  )

obj <- 
  assembler_start(
    community0, 
    control = control
  )

# run assembly
obj <- assembler_run(obj, nsteps =10)
```

## Analysis


Now lets' look at the results

How many species in the community?
```{r}
p$max_patch_lifetime
p$strategy_default$hmat
obj$community$traits
obj$community$birth_rate
```

```{r}
library(dplyr)
library(ggplot2)
landscape <- obj$community$fitness_approximate_points %>% as_tibble()
ggplot(landscape, aes(lma, fitness)) + 
  geom_line() +
  scale_x_log10() +
  geom_point(data = tibble(lma = obj$community$traits[,1], fitness = 0), col="red")
```

