
# Example of assembly for lma, using maxfit 

```{r}
#devtools::load_all("../plant-dev")
#devtools::load_all()

library(plant)
library(plant.assembly)
library(dplyr)
library(tidyr)
library(readr)
library(purrr)
library(ggridges)

source("ESA.R")
```

Establish grid

```{r}
pars <-
  expand_grid(
    trait = c("lma"),
    disturbance_interval = c(7.5, 10, 15, 20, 30),
    B_lf1 = c(0.8, 0.9, 1, 1.1, 1.2, 1.3)
  ) %>%
  mutate(
    path = file.path("output", trait, "base"),
    filename = sprintf("%s/%s-%s-0.rds", path, disturbance_interval, B_lf1)
  )

dir.create("output", FALSE)
write_csv(pars, "output/base.csv")
```


```{r}
pars <- read_csv("output/base.csv")

x <- pars %>% 
    filter(!file.exists(filename)) %>% 
    split(.$filename)

tmp <- parallell::mclapply(x, function(.x) f_assemble(.x$trait, .x$disturbance_interval, .x$B_lf1, .x$filename), mc.cores = 6)

#f_assemble("lma", 10, 0.8, "output/tmp2.rds")
```

Analysis

```{r}
source("ESA.R")

pars <- read_csv("output/base.csv") %>%
  filter(file.exists(filename))

out <- process_results(pars)

plot_landscapes(out$landscapes, out$residents) +
  facet_grid(vars(disturbance_interval), vars(B_lf1))

ggsave("output/figures/grid.png", height = 5, width=10)

```

```{r}
d <- 15

l2 <- 
  out$landscapes %>%
  filter(disturbance_interval == d) %>% 
  mutate(fitness= exp(fitness))

r2 <-
  out$residents %>%
  filter(disturbance_interval == d) %>%
  mutate(B_lf1 = B_lf1 + exp(fitness))

ggplot(l2, aes(x = trait_value, y = B_lf1, height = fitness, group= B_lf1)) +
  geom_ridgeline(stat = "identity", scale = 1) +
  geom_point(data = r2, col="red") +
  theme_classic() +
#    theme_ridges() +
  scale_x_log10() +
  xlab("LMA (kg/m2)") +
  ylab("Site productivity")

ggsave("output/figures/ridges-15.png", height = 3, width=6)

```

Plot assembled community
```{r}

filename <- "output/lma/base/15-1-0.rds"
obj <- readRDS(filename)
control <- obj$control

out <- run_scm_collect(obj$community$parameters)

out %>% tidy_patch()

landscapes <- 
  obj$history %>% 
  purrr:::map_df(~.x$fitness_points %>% as_tibble(), .id = "step") %>% mutate(trait_value =lma) %>%
  mutate(step= as.integer(step))

f_extract_residents <- function(.x) {
    if(nrow(.x$traits) == 0) return(tibble())
    tibble(
      trait_value = .x$traits[, 1],
      fitness = 
        approx(
          .x$fitness_points[,"lma"], 
          .x$fitness_points[, "fitness"], 
          .x$traits[, 1]
            )$y
  )
} 

residents <- 
  obj$history %>% 
  purrr:::map_df(.id = "step", f_extract_residents) %>%
  mutate(step= as.integer(step))

plot_landscapes(landscapes, residents) +
    facet_wrap(~step)

for(i in 1:17) {
  p <- plot_landscape_i(i)
  ggsave(plot=p, sprintf("output/figures/lma-assembly-%s.png", i), height = 2, width=4)
}


```



Modify environment for existing community

```{r}
filename <- "output/lma/base/15-1-0.rds"
obj <- readRDS(filename)
control <- obj$control
community <- obj$community 
B_lf1_new = 1.1

fitness1 <- 
  community$fitness_points %>% as_tibble() %>% mutate(step=1, trait_value=lma) 

# change env via hyper par
community$hyperpar <- make_FF16_hyperpar(B_lf1 = B_lf1_new)

community$fitness_points <- NULL
community <- plant.assembly:::community_prepare_fitness(community)

community2 <- plant.assembly:::community_prepare_approximate_fitness(community)

community3 <- plant.assembly:::community_run_to_equilibrium(community)

community3b <- plant.assembly:::community_prepare_approximate_fitness(community3)

residents1 <- tibble(lma = community$traits[, 1], fitness = approx(fitness1[[1]], fitness1[[2]], community$traits[, 1])$y) %>% mutate(step=1, trait_value=lma)

fitness3 <- community3b$fitness_points %>% as_tibble() %>% mutate(step = 1,trait_value=lma)

residents3 <- tibble(lma = community$traits[, 1], fitness = approx(fitness3[[1]], fitness3[[2]], community$traits[, 1])$y)%>% mutate(step = 1,trait_value=lma)

plot_landscape_i(1, fitness1, residents1) +
  geom_line(data = fitness3, col =  "#00BA38")

ggsave(sprintf("output/figures/lma-assembly-%s.png", 18), height = 2, width=4)


```

Continue Assembly with new situation

```{r}

filename2 <- "output/lma/base/15-1-1.rds"

f_assemble("lma", 15, 1.1, filename2, community3b)

obj2 <- readRDS(filename2)

community4 <- obj2$community

fitness4 <- community4$fitness_points %>% as_tibble() %>% mutate(step = 1,trait_value=lma)

residents4 <- tibble(lma = community4$traits[, 1], fitness = approx(fitness4[[1]], fitness4[[2]], community4$traits[, 1])$y) %>% mutate(step = 1,trait_value=lma)

plot_landscape_i(1, fitness1, residents1) +
  geom_line(data = fitness4, col =  "#00BA38") +
  geom_point(data = residents4, col = "#619CFF")

ggsave(sprintf("output/figures/lma-assembly-%s.png", 19), height = 2, width=4)

ggplot(fitness1, aes(lma, fitness)) +
  geom_line() +
  scale_x_log10() +
  geom_point(data = residents, col = "red") +
  # geom_line(data = fitness2, col = "blue") +
  geom_line(data = fitness3, col = "green") +
  geom_line(data = fitness4, col = "blue") +
  geom_point(data = residents4, col = "black")
  
```

