set.seed(1)
callr::callr("short.json", "short_out.json")
res <- jsonlite::fromJSON(readLines("short_out.json"))
cmp <- jsonlite::fromJSON(readLines("short_out.json.cmp"))
testthat::expect_equal(res, cmp)

set.seed(1)
callr::callr("long.json", "long_out.json")
res <- jsonlite::fromJSON(readLines("long_out.json"))
cmp <- jsonlite::fromJSON(readLines("long_out.json.cmp"))
testthat::expect_equal(res, cmp)
