// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dd99_fitness
NumericVector dd99_fitness(NumericVector x_mut, NumericVector x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_dd99_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(dd99_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// dd99_equilibrium
NumericVector dd99_equilibrium(NumericVector x_res, List pars);
RcppExport SEXP _regnans_dd99_equilibrium(SEXP x_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(dd99_equilibrium(x_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// dd99_nd_fitness
NumericVector dd99_nd_fitness(NumericMatrix x_mut, NumericMatrix x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_dd99_nd_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(dd99_nd_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// dd99_nd_equilibrium
NumericVector dd99_nd_equilibrium(NumericMatrix x_res, List pars);
RcppExport SEXP _regnans_dd99_nd_equilibrium(SEXP x_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(dd99_nd_equilibrium(x_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// gk98_fitness
NumericVector gk98_fitness(NumericVector x_mut, NumericVector x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_gk98_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gk98_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// gk98_equilibrium
NumericVector gk98_equilibrium(NumericVector x_res, List pars, int max_iter, double eps);
RcppExport SEXP _regnans_gk98_equilibrium(SEXP x_resSEXP, SEXP parsSEXP, SEXP max_iterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gk98_equilibrium(x_res, pars, max_iter, eps));
    return rcpp_result_gen;
END_RCPP
}
// gm99_fitness
NumericVector gm99_fitness(NumericVector x_mut, NumericVector x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_gm99_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(gm99_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// gm99_equilibrium
NumericVector gm99_equilibrium(NumericVector x_res, List pars, int max_iter, double eps);
RcppExport SEXP _regnans_gm99_equilibrium(SEXP x_resSEXP, SEXP parsSEXP, SEXP max_iterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gm99_equilibrium(x_res, pars, max_iter, eps));
    return rcpp_result_gen;
END_RCPP
}
// jj12_fitness
NumericVector jj12_fitness(NumericVector x_mut, NumericVector x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_jj12_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(jj12_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// jj12_equilibrium
NumericVector jj12_equilibrium(NumericVector x_res, List pars, int max_iter, double eps);
RcppExport SEXP _regnans_jj12_equilibrium(SEXP x_resSEXP, SEXP parsSEXP, SEXP max_iterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(jj12_equilibrium(x_res, pars, max_iter, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_regnans_dd99_fitness", (DL_FUNC) &_regnans_dd99_fitness, 4},
    {"_regnans_dd99_equilibrium", (DL_FUNC) &_regnans_dd99_equilibrium, 2},
    {"_regnans_dd99_nd_fitness", (DL_FUNC) &_regnans_dd99_nd_fitness, 4},
    {"_regnans_dd99_nd_equilibrium", (DL_FUNC) &_regnans_dd99_nd_equilibrium, 2},
    {"_regnans_gk98_fitness", (DL_FUNC) &_regnans_gk98_fitness, 4},
    {"_regnans_gk98_equilibrium", (DL_FUNC) &_regnans_gk98_equilibrium, 4},
    {"_regnans_gm99_fitness", (DL_FUNC) &_regnans_gm99_fitness, 4},
    {"_regnans_gm99_equilibrium", (DL_FUNC) &_regnans_gm99_equilibrium, 4},
    {"_regnans_jj12_fitness", (DL_FUNC) &_regnans_jj12_fitness, 4},
    {"_regnans_jj12_equilibrium", (DL_FUNC) &_regnans_jj12_equilibrium, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_regnans(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
