// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bird_log_fitness
NumericVector bird_log_fitness(NumericVector x_mut, NumericVector x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_bird_log_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(bird_log_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// bird_equilibrium
NumericVector bird_equilibrium(NumericVector x_res, List pars, int max_iter, double eps);
RcppExport SEXP _regnans_bird_equilibrium(SEXP x_resSEXP, SEXP parsSEXP, SEXP max_iterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(bird_equilibrium(x_res, pars, max_iter, eps));
    return rcpp_result_gen;
END_RCPP
}
// dd99_fitness
NumericVector dd99_fitness(NumericVector x_mut, NumericVector x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_dd99_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(dd99_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// dd99_equilibrium
NumericVector dd99_equilibrium(NumericVector x_res, List pars);
RcppExport SEXP _regnans_dd99_equilibrium(SEXP x_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(dd99_equilibrium(x_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// geritz_log_fitness
NumericVector geritz_log_fitness(NumericVector x_mut, NumericVector x_res, NumericVector n_res, List pars);
RcppExport SEXP _regnans_geritz_log_fitness(SEXP x_mutSEXP, SEXP x_resSEXP, SEXP n_resSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_mut(x_mutSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_res(n_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(geritz_log_fitness(x_mut, x_res, n_res, pars));
    return rcpp_result_gen;
END_RCPP
}
// geritz_equilibrium
NumericVector geritz_equilibrium(NumericVector x_res, List pars, int max_iter, double eps);
RcppExport SEXP _regnans_geritz_equilibrium(SEXP x_resSEXP, SEXP parsSEXP, SEXP max_iterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_res(x_resSEXP);
    Rcpp::traits::input_parameter< List >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(geritz_equilibrium(x_res, pars, max_iter, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_regnans_bird_log_fitness", (DL_FUNC) &_regnans_bird_log_fitness, 4},
    {"_regnans_bird_equilibrium", (DL_FUNC) &_regnans_bird_equilibrium, 4},
    {"_regnans_dd99_fitness", (DL_FUNC) &_regnans_dd99_fitness, 4},
    {"_regnans_dd99_equilibrium", (DL_FUNC) &_regnans_dd99_equilibrium, 2},
    {"_regnans_geritz_log_fitness", (DL_FUNC) &_regnans_geritz_log_fitness, 4},
    {"_regnans_geritz_equilibrium", (DL_FUNC) &_regnans_geritz_equilibrium, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_regnans(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
