# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bird model: log invasion fitness of mutants
#'
#' @param x_mut numeric vector of mutant trait values (arrival times)
#' @param x_res numeric vector of resident trait values
#' @param n_res numeric vector of resident equilibrium densities
#' @param pars list with a, x_opt, sigma, R0, K, p
#' @return numeric vector of log invasion fitness, one per mutant
#' @keywords internal
bird_log_fitness <- function(x_mut, x_res, n_res, pars) {
    .Call('_regnans_bird_log_fitness', PACKAGE = 'regnans', x_mut, x_res, n_res, pars)
}

#' Bird model: resident demographic equilibrium densities
#'
#' Single resident: closed form n* = K R(x)/(1-p). Multiple residents: iterate
#' the territory-competition recursion to its fixed point (the bird model has a
#' single limiting resource, so this generically resolves to competitive
#' exclusion of all but the strategy maximising R(x)C(x)).
#'
#' @param x_res numeric vector of resident trait values
#' @param pars list with a, x_opt, sigma, R0, K, p
#' @param max_iter maximum fixed-point iterations (multi-resident case)
#' @param eps convergence tolerance (multi-resident case)
#' @return numeric vector of equilibrium densities, one per resident
#' @keywords internal
bird_equilibrium <- function(x_res, pars, max_iter = 5000L, eps = 1e-12) {
    .Call('_regnans_bird_equilibrium', PACKAGE = 'regnans', x_res, pars, max_iter, eps)
}

