# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DD99 model: invasion fitness of mutants (a per-capita growth rate)
#'
#' @param x_mut numeric vector of mutant trait values
#' @param x_res numeric vector of resident trait values
#' @param n_res numeric vector of resident equilibrium densities
#' @param pars list with r, K0, x0, sigma_K, sigma_C
#' @return numeric vector of invasion fitness (=0 for a resident at equilibrium)
#' @keywords internal
dd99_fitness <- function(x_mut, x_res, n_res, pars) {
    .Call(`_regnans_dd99_fitness`, x_mut, x_res, n_res, pars)
}

#' DD99 model: resident demographic equilibrium densities
#'
#' Single resident: N* = K(x). Many residents: solve the linear system A N = K
#' with A_ij = C(x_i - x_j) (negative densities, i.e. strategies that cannot
#' coexist, are clamped to zero).
#'
#' @param x_res numeric vector of resident trait values
#' @param pars list with r, K0, x0, sigma_K, sigma_C
#' @return numeric vector of equilibrium densities
#' @keywords internal
dd99_equilibrium <- function(x_res, pars) {
    .Call(`_regnans_dd99_equilibrium`, x_res, pars)
}

#' DD99 model (nD): invasion fitness of mutants (a per-capita growth rate)
#'
#' @param x_mut numeric matrix of mutant trait values (rows = mutants, cols = traits)
#' @param x_res numeric matrix of resident trait values
#' @param n_res numeric vector of resident equilibrium densities
#' @param pars list with r, K0, x0, sigma_K, sigma_C (the last three length-k)
#' @return numeric vector of invasion fitness (=0 for a resident at equilibrium)
#' @keywords internal
dd99_nd_fitness <- function(x_mut, x_res, n_res, pars) {
    .Call(`_regnans_dd99_nd_fitness`, x_mut, x_res, n_res, pars)
}

#' DD99 model (nD): resident demographic equilibrium densities
#'
#' @param x_res numeric matrix of resident trait values
#' @param pars list with r, K0, x0, sigma_K, sigma_C (the last three length-k)
#' @return numeric vector of equilibrium densities
#' @keywords internal
dd99_nd_equilibrium <- function(x_res, pars) {
    .Call(`_regnans_dd99_nd_equilibrium`, x_res, pars)
}

#' GK98 soft-selection model: log invasion fitness of mutants
#'
#' @param x_mut numeric vector of mutant trait values
#' @param x_res numeric vector of resident trait values
#' @param n_res numeric vector of resident equilibrium abundances
#' @param pars list with sigma, mu (patch optima), K (patch capacities)
#' @return numeric vector of log invasion fitness (=0 for resident at equilibrium)
#' @keywords internal
gk98_fitness <- function(x_mut, x_res, n_res, pars) {
    .Call(`_regnans_gk98_fitness`, x_mut, x_res, n_res, pars)
}

#' GK98 soft-selection model: resident equilibrium abundances
#'
#' Iterates the soft-selection recursion (Eq 19) to its fixed point; total
#' abundance is conserved at sum(K). Single resident: N* = sum(K).
#'
#' @param x_res numeric vector of resident trait values
#' @param pars list with sigma, mu (patch optima), K (patch capacities)
#' @param max_iter maximum fixed-point iterations
#' @param eps convergence tolerance
#' @return numeric vector of equilibrium abundances
#' @keywords internal
gk98_equilibrium <- function(x_res, pars, max_iter = 5000L, eps = 1e-12) {
    .Call(`_regnans_gk98_equilibrium`, x_res, pars, max_iter, eps)
}

#' GM99 seed-size model: log invasion fitness of mutants
#'
#' @param x_mut numeric vector of mutant seed sizes
#' @param x_res numeric vector of resident seed sizes
#' @param n_res numeric vector of resident equilibrium densities (seeds/site)
#' @param pars list with R, alpha, beta
#' @return numeric vector of log invasion fitness (=0 for resident at equilibrium;
#'   -Inf for non-viable mutants where s(x) = 0)
#' @keywords internal
gm99_fitness <- function(x_mut, x_res, n_res, pars) {
    .Call(`_regnans_gm99_fitness`, x_mut, x_res, n_res, pars)
}

#' GM99 seed-size model: resident equilibrium densities (seeds/site)
#'
#' Single resident: solve (R/x) s(x) (1 - exp(-N))/N = 1 by bisection (N* = 0 if
#' the strategy is non-viable). Many residents: Newton's method on log W_i = 0
#' in log-N space, with a numerical Jacobian. Newton converges quadratically so
#' only ~10-30 steps are needed regardless of resident count, vs. thousands for
#' the previous fixed-point iteration.
#'
#' @param x_res numeric vector of resident seed sizes
#' @param pars list with R, alpha, beta
#' @param max_iter maximum Newton iterations (multi-resident case)
#' @param eps convergence tolerance on max |log W_i|
#' @return numeric vector of equilibrium densities
#' @keywords internal
gm99_equilibrium <- function(x_res, pars, max_iter = 200L, eps = 1e-10) {
    .Call(`_regnans_gm99_equilibrium`, x_res, pars, max_iter, eps)
}

#' JJ12 bird model: log invasion fitness of mutants
#'
#' @param x_mut numeric vector of mutant trait values (arrival times)
#' @param x_res numeric vector of resident trait values
#' @param n_res numeric vector of resident equilibrium densities
#' @param pars list with a, x_opt, sigma, R0, K, p
#' @return numeric vector of log invasion fitness, one per mutant
#' @keywords internal
jj12_fitness <- function(x_mut, x_res, n_res, pars) {
    .Call(`_regnans_jj12_fitness`, x_mut, x_res, n_res, pars)
}

#' JJ12 bird model: resident demographic equilibrium densities
#'
#' Single resident: closed form n* = K R(x)/(1-p). Multiple residents: iterate
#' the territory-competition recursion to its fixed point (a single limiting
#' resource, so this generically resolves to competitive exclusion of all but
#' the strategy maximising R(x)C(x)).
#'
#' @param x_res numeric vector of resident trait values
#' @param pars list with a, x_opt, sigma, R0, K, p
#' @param max_iter maximum fixed-point iterations (multi-resident case)
#' @param eps convergence tolerance (multi-resident case)
#' @return numeric vector of equilibrium densities, one per resident
#' @keywords internal
jj12_equilibrium <- function(x_res, pars, max_iter = 5000L, eps = 1e-12) {
    .Call(`_regnans_jj12_equilibrium`, x_res, pars, max_iter, eps)
}

